### ISSUE TITLE
Get positions and return total of all position values in dai

### ISSUE THREAD

**Issue by KadenZipfel** [KadenZipfel/defi-insure#3]
We'll start by doing this with Compound and move to other protocols afterwards. 

Given a user's address, we want to get all their lending positions on compound and determine the value in Dai. This will give us the ability to automatically insure the user from the smart contract. We will use Compound's API `https://api.compound.finance/api/v2/account?addresses[]=0x00...` along with Kyber's API's.

Steps involved:

- Accept a user address as input
- Query Compound API for the user's positions
- From the user's positions, get the underlying tokens and values
- Convert underlying token values to equivalent value in Dai using Kyber
  - You'll have to convert from token => Eth => Dai
- Add all the token values together to return a total value in Dai.

Much of this process is already completed in `getCompoundPositions()` in `App.js`. Feel free to modify existing code and clean it up if possible. Currently it's scattered with callbacks because of how forEach affects async/await. It might be easiest to simply comment out the current function and create a new one in place of it.

**Comment by mmitrasish** [comment]
I'll start working on this. Also I'm thinking of creating a separate file for apis. It would help in managing the app later.

**Comment by KadenZipfel** [comment]
https://github.com/KadenZipfel/defi-insure/pull/4
