### ISSUE TITLE
Query nexus mutual for insurance quotes

### ISSUE THREAD

**Issue by KadenZipfel** [KadenZipfel/defi-insure#7]
We want to take the value in dai that we've got from users positions, and from each protocol give users a quote on the price of insurance for that position. This will later allow users to click to insure that position via a smart contract transaction.

Nexus Mutual doesn't seem to have docs on their API yet so we'll have to message this guy Hugh | Nexus Mutual#3031 to get this setup.

**Comment by mmitrasish** [comment]
Hey can you tell me the value for fields in the api to get the quotes?

**Comment by KadenZipfel** [comment]
https://github.com/KadenZipfel/defi-insure/pull/8
